_target_: lightning_classes.model.Classification.HierarchicalSSOCClassifier

model:
  filepath: ${paths.model_dir}/distilbert/
  tokenizer: ${paths.model_dir}/distilbert/

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: transformers.get_scheduler
  _partial_: true
  name: linear
  optimizer: optimizer

net:
  _target_: lightning_classes.model.components.Hierarchical.V2pt2
  lm_filepath: ${paths.model_dir}/distilbert/
  max_level: 5
  
other_params:
  num_warmup_steps: 0
  num_training_steps: 200
